### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by mostafaebrahimi** [aminsoheyli/Instagram-App#1]
Hi @ErfanNzr 
Did you start to document this project ?!

**Comment by AliSeraji** [comment]
What happens if he documents his project?

**Comment by mostafaebrahimi** [comment]
@nothing babe :D

**Comment by mostafaebrahimi** [comment]
What did you do babe ? 
@ErfanNzr

**Comment by aminsoheyli** [comment]
@ErfanNzr 
Did you do it?

**Comment by mostafaebrahimi** [comment]
@aminsoheyli 
ERROR 404
Your requested person has not been found :)

**Comment by aminsoheyli** [comment]
4️⃣0️⃣4️⃣😂
