### ISSUE TITLE
clickup task

### ISSUE THREAD

**Issue by mostafaebrahimi** [aminsoheyli/Instagram-App#2]
Write a list of to do and roadmap on [clickup](https://clickup.com)
@aminsoheyli

1. learn clickup
2. create a one month workspace
3. create list of tasks and road map base on real Instagram until next month

please do it until tomorrow
tnx in advance

**Comment by aminsoheyli** [comment]
@mostafaebrahimi 
What's the advantages of clickup vs trello?

**Comment by aminsoheyli** [comment]
@mostafaebrahimi 
Your clickup username/email?

**Comment by mostafaebrahimi** [comment]
Hi @aminsoheyli 
Clickup is based on some of the best project management like Kanban, Agile and... techs but Trello is not

**Comment by mostafaebrahimi** [comment]
@aminsoheyli been sent at Telegram

**Comment by aminsoheyli** [comment]
https://github.com/aminsoheyli/Instagram-App/issues/2#issue-403760819

**Comment by aminsoheyli** [comment]
> Write a list of to do and roadmap on [clickup](https://clickup.com)
> @aminsoheyli
> 
> 1. learn clickup
> 2. create a one month workspace
> 3. create list of tasks and road map base on real Instagram until next month
> 
> please do it until tomorrow
> tnx in advance

@mostafaebrahimi 
### > As you can see in the below clickup's link, it has almost done!
[Instagram-GUI](https://app.clickup.com/1854446/d/b?p=1926473&c=2265954&s=-1)

**Comment by mostafaebrahimi** [comment]
Hi @aminsoheyli 
Thanks bro
