### ISSUE TITLE
A good circular image view

### ISSUE THREAD

**Issue by aminsoheyli** [aminsoheyli/Instagram-App#3]
### Do you know any good circular image view?

**Comment by aminsoheyli** [comment]
Like this:
![circular](https://user-images.githubusercontent.com/42641117/52066825-8ea0d700-258e-11e9-8bbc-85f5b7c95117.PNG)

**Comment by aminsoheyli** [comment]
They are saying from control room:

> Use [Glide](https://github.com/bumptech/glide), also see [Glide's docs and tutorials](https://bumptech.github.io/glide/).
![glide_logo](https://user-images.githubusercontent.com/42641117/52087532-f3742580-25be-11e9-974e-e487a2e822af.png)

**Comment by mostafaebrahimi** [comment]
@aminsoheyli 
`control room ` 🤣

**Comment by mostafaebrahimi** [comment]
@aminsoheyli has been done ?!
