### ISSUE TITLE
Add fake data generator

### ISSUE THREAD

**Issue by mostafaebrahimi** [aminsoheyli/Instagram-App#6]
Hi.
please add this lib as data generator
Tnx
[https://github.com/DiUS/java-faker](Generator)

**Comment by aminsoheyli** [comment]
> Hi.
> please add this lib as data generator
> Tnx
> [https://github.com/DiUS/java-faker](Generator)

### @mostafaebrahimi 

### Yeah, It has been added to the project.

**Comment by mostafaebrahimi** [comment]
Thanks

**Comment by aminsoheyli** [comment]
Your welcome🙋🏻‍♂️
