### ISSUE TITLE
Load images as Bitmap with Glide

### ISSUE THREAD

**Issue by aminsoheyli** [aminsoheyli/Instagram-App#7]
I want to load images as Bitmaps with Glide, before calling the recycler view adapter.
I do that as below:
` Glide.with(getContext()).asBitmap().load(faker.internet().image()).submit().get();`

But I encountered an error:
`You must call this method on a background `

I tried many ways, but the problem is still exist.
###  **Please, see the last commit on the update_profile_fragment branch.**

**Comment by mostafaebrahimi** [comment]
@aminsoheyli Why as a bitmap ?!

**Comment by aminsoheyli** [comment]
@mostafaebrahimi 
I don't know.
Do you know a better way?

**Comment by mostafaebrahimi** [comment]
@aminsoheyli Images url is enough!
```java 
Glide.with(this).load(img_url).into(image_container)
```
